export const actionTypes = {
  IS_LOADING_ENABLE_REQUEST: 'IS_LOADING_ENABLE_REQUEST',
  IS_LOADING_ENABLE_SUCCESS: 'IS_LOADING_ENABLE_SUCCESS',
  IS_LOADING_DISABLE_REQUEST: 'IS_LOADING_DISABLE_REQUEST',
  IS_LOADING_DISABLE_SUCCESS: 'IS_LOADING_DISABLE_SUCCESS',
  AUTHENTICATION_401: 'AUTHENTICATION_401',
  RESET_COMMON: 'RESET_COMMON',
};
export default actionTypes;
