export const LOCAL_STORAGE_KEY = {
  LEARNER_SELECTED_ID: 'LEARNER_SELECTED_ID',
  CURRENT_USER: 'CURRENT_USER',
  USER_TIMEZONE: 'USER_TIMEZONE',
};
export const ROLE = {
  ROLE_TEACHER: 'ROLE_TEACHER',
  ROLE_PARENT: 'ROLE_PARENT',
  ROLE_ADMIN: 'ROLE_ADMIN',
};

export const ROUTE_PAGE = {
  ROUTE_HOME: '/',
  ROUTE_LOGIN: '/login',
  ROUTE_FORGOT_PASSWORD: 'forgot-password',
  ROUTE_CLASSLIST: '/classList',
  ROUTE_OPEN_SLOT: '/open-slot',
  ROUTE_PROFILE: '/profile',
  ROUTE_SETTING: '/setting',
  ROUTE_VIRTUALCLASSROOM: '/classroom/:id',
  ROUTE_CLASSROOM: '/classroom/',
};

export const DAY_FORMAT = {
  FORMAT_DATE_VIEW: 'DD/MM/YYYY',
  FORMAT_DATE_POST: 'YYYY-MM-DD',
  CALENDAR_YEAR_FORMAT: 'YYYY',
  CALENDAR_MONTH_YEAR_FORMAT: 'MMMM-YYYY',
  BACK_END_START_TIME_FORMAT: 'YYYY-MM-DD 00:00',
  BACK_END_END_TIME_FORMAT: 'YYYY-MM-DD 23:59',
  DATE_TIME_BACK_END_FORMAT: 'YYYY-MM-DD HH:mm',
  DATE_TIME_DISPLAY_FORMAT: 'YYYY-MM-DD HH:mm',
};

export const TIME = {
  ONE_HOUR: 3600,
};
