export const API_URL = {
  LOGIN: 'auth/login/',
};

export const STATUS_AUTH = {
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  ACCOUNT_NOT_EXIST: 'ACCOUNT_NOT_EXIST',
};
